skip_commits:
  files:
    - README.md

image: WMF 5

version: 0.0.{build}
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.split("-")[0])"
    } 

environment:
  NugetApiKey:
    secure: wz8VOuRxEgPd7evPVcWYTqpW/tqigqdZpS9Stmhb2K2bXkOAHm07on4Hmy11EysF
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN

install:
- ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose

build_script:
  - cd build
  - ps: ./build.ps1 -ScriptArgs '--FileVersion="$env:APPVEYOR_BUILD_VERSION"' 
  
artifacts:
  - path: bin\*.nupkg
    name: Cake.Deploy.Variables

deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: Cake.Deploy.Variables
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: Cake.Deploy.Variables
    on:
      appveyor_repo_tag: true
