version: 0.0.{build}
image: Visual Studio 2017
skip_commits:
  files:
    - README.md
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.split("-")[0])"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  namespace: Cake.Deploy.Variables
  cc: opencover
  NugetApiKey:
    secure: wz8VOuRxEgPd7evPVcWYTqpW/tqigqdZpS9Stmhb2K2bXkOAHm07on4Hmy11EysF
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN
install:
- ps: >-
    choco install codecov
build_script:
- ps: >-
    dotnet build ./src/$env:namespace.sln

    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        dotnet pack ./src/$env:namespace --no-build -p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
    }
    else
    {
        dotnet pack ./src/$env:namespace --no-build -p:PackageVersion=$env:APPVEYOR_BUILD_VERSION
    }
test_script:
- cmd: >-
    dotnet test ./src/%namespace%.Test  /p:CollectCoverage=true /p:CoverletOutputFormat=%cc% /p:Exclude="[xunit*]*" /p:CoverletOutput=%appveyor_build_folder%\%cc%\%namespace%.xml

    codecov -f %appveyor_build_folder%\%cc%\%namespace%.xml --flag unittests
artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key: $(NugetApiKey)
    on:
      appveyor_repo_tag: true
